[package]
name = "db_handler"
version = "0.1.0"
authors = ["muller95 <muller95@yandex.ru>"]

[lib]
name = "db_handler"
path = "src/db_handler.rs"
crate-type = ["dylib"]
    
[dependencies]
rmp_bind = { path = "../rmp_bind" }
libc = "0.2"
serde_json = "1.0"
chrono = "0.3"
juniper = "0.8.1"
lmdb-rs = "0.7.6"