[package]
name = "veda-lmdb-server"
version = "0.1.0"
authors = ["Vadim <muller95@yandex.ru>"]

[dependencies]
lmdb-rs = "0.7.6"
rmp_bind = { path = "../rmp_bind" }
cbor = "0.4.0"
rustc-serialize = "0.3"